

export function normalizeColumnName(key: string): string {
  return key.replace(/[\s\.]+/g, '_').toLowerCase().trim();
}

export const SPROUT_INVENTORY_COLUMNS = [
  'enterprisesupplier',
  'totalquantityonhand',
  'totalquantityonpurchaseorder',
  'totalweeksonhand',
  'totalweeksonpo',
  'totalquantityonsalesorder',
  'brand',
  'brandtotalquantityonhand',
  'brandtotalquantityonpurchaseorder',
  'brandtotalweeksonhand',
  'brandtotalweeksonpo',
  'brandtotalquantityonsalesorder',
  'dc',
  'dctotalquantityonhand',
  'dctotalquantityonpurchaseorder',
  'dctotalweeksonhand',
  'dctotalweeksonpo',
  'dctotalquantityonsalesorder',
  'textbox31',
  'upc',
  'productdescription',
  'vendorcasepack',
  'quantityonhand',
  'quantityonpurchaseorder',
  'weeksonhand',
  'weeksonpo',
  'quantityonsalesorder',
  'downloaded_on',
  'sku',
  'box_per_case',
  'material',
  'product_category',
  'product_sub_category',
  'product_type',
  'esn',
  'supplier',
  'broker',
  'itemdescription',
  'reason',
  'note',
  'pack',
  'size',
  'uom',
  'guaranteedshelflifedaystocustomer',
  'sellbydate',
  'daysremainingtoshiptocustomer',
  'unitsalesvelocityperday',
  'unitsonhandwithnoforecastdemand',
];

export const SPROUT_CHAIN_STORE_COLUMNS = [
  'file_month',
  'retailer',
  'retailer_area',
  'product_description',
  'fill_rate_vendor_cost',
  'ordered_vendor_cost',
  'shipped_vendor_cost',
  'upc',
  'fill_rate_quantity',
  'ordered_quantity',
  'shipped_quantity',
  'fill_rate_list_wholesale',
  'ordered_list_wholesale',
  'shipped_list_wholesale',
  'sku',
  'box_per_case',
  'material',
  'product_category',
  'product_sub_category',
  'product_type',
  'ordered_case_cost_vendor_cost',
  'ordered_case_cost_list_wholesale',
  'markup',
];

export const WAITROSE_COMMERCE_COLUMNS = [
  'distributors',
  'retailers_x',
  'po_number',
  'po_date',
  'po_requested_delivery_date',
  'po_amount_vat',
  'convertor_x',
  'po_amount',
  'po_status',
  'actual_fulfillment_date',
  'invoice_number',
  'invoice_date',
  'invoice_amount_vat',
  'invoice_amount',
  'shipping_city',
  'po_link',
  'manual_invoice_link',
  'invoices_link',
  'year_month_po',
  'delay_days',
  'po_delivery_status',
  'retailers_y',
  'article_waitrose_id',
  'skus',
  'upc_gtin',
  'sku_qty_quantity_expressed_in_ou',
  'po_case_price_net_purchase_price',
  'net_purchase_price',
  'convertor_y',
  'vat_20',
  'po_sales_with_vat',
  'line_no',
  'invoice_qty',
  'invoice_case_price',
  'status',
  'total_sales_with_vat',
  'box_per_case_sku_ou',
  'qty_diff',
  'amt_diff',
  'common_po_date',
  'common_invoice_date',
  'new_po_delivery_status',
  'new_status',
];

export const SPS_COMMERCE_COLUMNS = [
  'distributors',
  'retailers',
  'po_number',
  'po_date',
  'po_requested_delivery_date',
  'po_amount',
  'po_status',
  'actual_fulfillment_date',
  'invoice_number',
  'invoice_date',
  'invoice_amount',
  'shipping_city',
  'shipping_state',
  'shipping_state_code',
  'shipping_country',
  'shipping_country_code',
  'shipping_postal_code',
  'po_link',
  'manual_invoice_link',
  'sps_invoices',
  'manual_invoice_link1',
  'year_month_po',
  'delay_days',
  'po_delivery_status',
  'upc_gtin',
  'sku',
  'sku_qty',
  'po_case_price',
  'po_sales',
  'invoice_qty',
  'invoice_case_price',
  'status',
  'total_sales',
  'box_per_case',
  'location',
  'warehouse',
  'qty_diff',
  'amt_diff',
  'channel',
  'unit_list_cost',
  'common_po_date',
  'common_invoice_date',
  'srp',
  'new_po_delivery_status',
  'new_status',
];

export function validateColumns(fileColumns: string[], requiredColumns: readonly string[]) {
  const requiredSet = new Set(requiredColumns);
  const fileSet = new Set(fileColumns.map(normalizeColumnName));

  const missingColumns = requiredColumns.filter((col) => !fileSet.has(col));
  const extraColumns = [...fileSet].filter((col) => !requiredSet.has(col));

  return {
    valid: missingColumns.length === 0,
    missingColumns,
    extraColumns,
  };
}
