

export function normalizeColumnName(key: string): string {
  // Strip UTF-8 BOM first — otherwise [\s] replaces it with leading "_"
  return key.replace(/^\uFEFF/, '').trim().replace(/[\s\.]+/g, '_').toLowerCase();
}

export const SPROUT_INVENTORY_COLUMNS = [
  'enterprisesupplier',
  'totalquantityonhand',
  'totalquantityonpurchaseorder',
  'totalweeksonhand',
  'totalweeksonpo',
  'totalquantityonsalesorder',
  'brand',
  'brandtotalquantityonhand',
  'brandtotalquantityonpurchaseorder',
  'brandtotalweeksonhand',
  'brandtotalweeksonpo',
  'brandtotalquantityonsalesorder',
  'dc',
  'dctotalquantityonhand',
  'dctotalquantityonpurchaseorder',
  'dctotalweeksonhand',
  'dctotalweeksonpo',
  'dctotalquantityonsalesorder',
  'textbox31',
  'upc',
  'productdescription',
  'vendorcasepack',
  'quantityonhand',
  'quantityonpurchaseorder',
  'weeksonhand',
  'weeksonpo',
  'quantityonsalesorder',
  'downloaded_on',
  'sku',
  'box_per_case',
  'material',
  'product_category',
  'product_sub_category',
  'product_type',
  'esn',
  'supplier',
  'broker',
  'itemdescription',
  'reason',
  'note',
  'pack',
  'size',
  'uom',
  'guaranteedshelflifedaystocustomer',
  'sellbydate',
  'daysremainingtoshiptocustomer',
  'unitsalesvelocityperday',
  'unitsonhandwithnoforecastdemand',
];

export const SPROUT_CHAIN_STORE_COLUMNS = [
  'file_month',
  'retailer',
  'retailer_area',
  'product_description',
  'fill_rate_vendor_cost',
  'ordered_vendor_cost',
  'shipped_vendor_cost',
  'upc',
  'fill_rate_quantity',
  'ordered_quantity',
  'shipped_quantity',
  'fill_rate_list_wholesale',
  'ordered_list_wholesale',
  'shipped_list_wholesale',
  'sku',
  'box_per_case',
  'material',
  'product_category',
  'product_sub_category',
  'product_type',
  'ordered_case_cost_vendor_cost',
  'ordered_case_cost_list_wholesale',
  'markup',
];

export const WAITROSE_COMMERCE_COLUMNS = [
  'distributors',
  'retailers_x',
  'po_number',
  'po_date',
  'po_requested_delivery_date',
  'po_amount_vat',
  'convertor_x',
  'po_amount',
  'po_status',
  'actual_fulfillment_date',
  'invoice_number',
  'invoice_date',
  'invoice_amount_vat',
  'invoice_amount',
  'shipping_city',
  'po_link',
  'manual_invoice_link',
  'invoices_link',
  'year_month_po',
  'delay_days',
  'po_delivery_status',
  'retailers_y',
  'article_waitrose_id',
  'skus',
  'upc_gtin',
  'sku_qty_quantity_expressed_in_ou',
  'po_case_price_net_purchase_price',
  'net_purchase_price',
  'convertor_y',
  'vat_20',
  'po_sales_with_vat',
  'line_no',
  'invoice_qty',
  'invoice_case_price',
  'status',
  'total_sales_with_vat',
  'box_per_case_sku_ou',
  'qty_diff',
  'amt_diff',
  'common_po_date',
  'common_invoice_date',
  'new_po_delivery_status',
  'new_status',
];

export const SPS_COMMERCE_COLUMNS = [
  'distributors',
  'retailers',
  'po_number',
  'po_date',
  'po_requested_delivery_date',
  'po_amount',
  'po_status',
  'actual_fulfillment_date',
  'invoice_number',
  'invoice_date',
  'invoice_amount',
  'shipping_city',
  'shipping_state',
  'shipping_state_code',
  'shipping_country',
  'shipping_country_code',
  'shipping_postal_code',
  'po_link',
  'manual_invoice_link',
  'sps_invoices',
  'manual_invoice_link1',
  'year_month_po',
  'delay_days',
  'po_delivery_status',
  'upc_gtin',
  'sku',
  'sku_qty',
  'po_case_price',
  'po_sales',
  'invoice_qty',
  'invoice_case_price',
  'status',
  'total_sales',
  'box_per_case',
  'location',
  'warehouse',
  'qty_diff',
  'amt_diff',
  'channel',
  'unit_list_cost',
  'common_po_date',
  'common_invoice_date',
  'srp',
  'new_po_delivery_status',
  'new_status',
];

export const WALMART_SCINTILLA_INVENTORY_COLUMNS = [
  'walmart_calendar_year',
  'walmart_calendar_month',
  'walmart_calendar_week',
  'report_date',
  'distribution_center_name',
  'ecomm_upc_number',
  'product_name',
  'available_to_sell_quantity_this_year',
  'available_to_sell_quantity_this_year_eop',
  'on_hand_unit_quantity_this_year',
  'on_hand_unit_quantity_this_year_eop',
  'walmart_sku',
  'ecosoul_sku',
  'year',
  'month',
];

export const WALMART_SCINTILLA_ORDER_FORECAST_COLUMNS = [
  'sugg_order_dt',
  'store_dc_nbr',
  'store_dc_type',
  'dc_nm',
  'dc_city_name',
  'wm_item_nbr',
  'product_description',
  'order_place_dt',
  'sched_arvl_dt',
  'vendor_pack_quantity',
  'vendor_name',
  'order_each_quantity',
  'walmart_sku',
  'ecosoul_sku',
  'month',
  'year',
  'item_number',
];

export const WALMART_SCINTILLA_SALES_COLUMNS = [
  'walmart_calendar_year',
  'walmart_calendar_month',
  'walmart_calendar_week',
  'business_date',
  'walmart_item_number',
  'product_description',
  'vendor_pack_quantity',
  'vendor_name',
  'auth_based_item_quantity_this_year',
  'auth_based_net_sales_amount_this_year',
  'shipped_based_net_sales_amount_this_year',
  'shipped_based_quantity_this_year',
  'walmart_sku',
  'ecosoul_sku',
  'year',
  'month',
  'unnamed_12',
  'unnamed_13',
  'unnamed_14',
  'unnamed_15',
  'walmart_calendar_year_1',
  'walmart_calendar_year_2',
  'walmart_calendar_year_3',
  'item_number',
];

export const WALMART_SCINTILLA_SKU_COLUMNS = [
  'item_number',
  'walmart_sku',
  'ecosoul_sku',
  'upc',
  'ecomm_upc_number',
  'pack',
  'unit_cost',
];

export const WALMART_SCINTILLA_STORE_SALES_COLUMNS = [
  'walmart_calendar_week',
  'walmart_calendar_year',
  'walmart_calendar_month',
  'business_date',
  'name_of_the_dc',
  'item_name',
  'walmart_item_number',
  'vendor_pack_quantity',
  'city_name',
  'vendor_number',
  'max_shelf_quantity_this_year',
  'dollar_per_str_with_sales_per_week_or_per_day_ly',
  'dollar_per_str_with_sales_per_week_or_per_day_ty',
  'dollar_per_store_per_week_or_per_day_last_year',
  'dollar_per_store_per_week_or_per_day_this_year',
  'units_per_str_with_sales_per_week_or_per_day_ly',
  'units_per_str_with_sales_per_week_or_per_day_ty',
  'units_per_store_per_week_or_per_day_last_year',
  'units_per_store_per_week_or_per_day_this_year',
  'instock_percentage_this_year',
  'instock_percentage_last_year',
  'store_on_hand_quantity_this_year',
  'store_in_warehouse_quantity_this_year',
  'pos_quantity_this_year',
  'pos_sales_this_year',
  'pos_store_count_this_year',
  'scan_count_this_year',
  'walmart_sku',
  'ecosoul_sku',
  'year',
  'month',
  'walmart_calendar_quarter',
  'item_number',
];
export function validateColumns(fileColumns: string[], requiredColumns: readonly string[]) {
  const requiredSet = new Set(requiredColumns);
  const fileSet = new Set(fileColumns.map(normalizeColumnName));

  const missingColumns = requiredColumns.filter((col) => !fileSet.has(col));
  const extraColumns = [...fileSet].filter((col) => !requiredSet.has(col));

  return {
    valid: missingColumns.length === 0,
    missingColumns,
    extraColumns,
  };
}
