export function normalizeColumnName(key: string): string {
  return key.replace(/^\uFEFF/, '').replace(/[\s\.]+/g, '_').toLowerCase().trim();
}

function hijackerColumns(): string[] {
  const cols: string[] = [];
  for (let i = 1; i <= 20; i++) {
    cols.push(`hijacker_${i}`, `hijacker_${i}_price`, `hijacker_${i}_moq`);
  }
  return cols;
}

export const PATTEX_BUYBOX_COLUMNS = [
  'asin',
  'brand',
  'product_sub_category',
  'vendor_confirmation_%',
  'po_received_amount',
  'po_received_units',
  'open_pos',
  'receive_fill_rate',
  'overall_vendor_lead_time_(days)',
  'aged_90+_days_sellable_inventory',
  'aged_90+_days_sellable_units',
  'sellable_inventory_amount',
  'available_inventory',
  'unsellable_on_hand_inventory_amount',
  'unsellable_on_hand_units',
  'date',
  'product_name',
  'product_category',
  'pack_type',
  'pack_size',
  'sc_ideal_price',
  'vc_ideal_price',
  'sales_channel',
  'in_stock_flag',
  'cumulative_instock_days',
  'day_of_month',
  'instock_rate',
  'total_sales',
  'total_units',
  'sell_through',
  'dos',
  'oos_date',
  'min_available_qty',
  'max_available_qty',
  'stock_status',
  'no/low_stock_wt_open_pos',
  'no/low_stock_wt_no_open_pos',
  'current_owner',
  'current_owner_price',
  'current_owner_moq',
  ...hijackerColumns(),
  'sku',
  'fnsku',
  'condition',
  'your_price',
  'mfn_listing_exists',
  'mfn_fulfillable_quantity',
  'afn_listing_exists',
  'afn_warehouse_quantity',
  'afn_fulfillable_quantity',
  'afn_unsellable_quantity',
  'afn_reserved_quantity',
  'afn_total_quantity',
  'per_unit_volume',
  'afn_inbound_working_quantity',
  'afn_inbound_shipped_quantity',
  'afn_inbound_receiving_quantity',
  'afn_researching_quantity',
  'afn_reserved_future_supply',
  'afn_future_supply_buyable',
  'store',
  'reserved_qty',
  'reserved_customerorders',
  'reserved_fc_transfers',
  'reserved_fc_processing',
  'units_shipped_t30',
  'units_shipped_t60',
  'units_shipped_t90',
] as const;

export const PATTEX_REVENUE_COLUMNS = [
  'asin',
  'brand',
  'product_sub_category',
  'vendor_confirmation_%',
  'po_received_amount',
  'po_received_units',
  'open_pos',
  'receive_fill_rate',
  'overall_vendor_lead_time_(days)',
  'aged_90+_days_sellable_inventory',
  'aged_90+_days_sellable_units',
  'sellable_inventory_amount',
  'available_inventory',
  'unsellable_on_hand_inventory_amount',
  'unsellable_on_hand_units',
  'date',
  'sales_channel',
  'in_stock_flag',
  'cumulative_instock_days',
  'day_of_month',
  'instock_rate',
  'total_sales',
  'total_units',
  'sell_through',
  'dos',
  'oos_date',
  'min_available_qty',
  'max_available_qty',
  'stock_status',
  'no/low_stock_wt_open_pos',
  'no/low_stock_wt_no_open_pos',
  'ads_sales',
  'ads_unit_sold',
  'ads_spend',
  'organic_sale',
  'product_name',
  'product_category',
  'pack_type',
  'pack_size',
  'sc_ideal_price',
  'vc_ideal_price',
  'sku',
  'fnsku',
  'condition',
  'your_price',
  'mfn_listing_exists',
  'mfn_fulfillable_quantity',
  'afn_listing_exists',
  'afn_warehouse_quantity',
  'afn_fulfillable_quantity',
  'afn_unsellable_quantity',
  'afn_reserved_quantity',
  'afn_total_quantity',
  'per_unit_volume',
  'afn_inbound_working_quantity',
  'afn_inbound_shipped_quantity',
  'afn_inbound_receiving_quantity',
  'afn_researching_quantity',
  'afn_reserved_future_supply',
  'afn_future_supply_buyable',
  'store',
  'reserved_qty',
  'reserved_customerorders',
  'reserved_fc_transfers',
  'reserved_fc_processing',
  'units_shipped_t30',
  'units_shipped_t60',
  'units_shipped_t90',
] as const;

export const PATTEX_INVENTORY_COLUMNS = [
  'sku',
  'fnsku',
  'asin',
  'condition',
  'your_price',
  'mfn_listing_exists',
  'mfn_fulfillable_quantity',
  'afn_listing_exists',
  'afn_warehouse_quantity',
  'afn_fulfillable_quantity',
  'afn_unsellable_quantity',
  'afn_reserved_quantity',
  'afn_total_quantity',
  'per_unit_volume',
  'afn_inbound_working_quantity',
  'afn_inbound_shipped_quantity',
  'afn_inbound_receiving_quantity',
  'afn_researching_quantity',
  'afn_reserved_future_supply',
  'afn_future_supply_buyable',
  'store',
  'date',
  'reserved_qty',
  'reserved_customerorders',
  'reserved_fc_transfers',
  'reserved_fc_processing',
  'available_inventory',
  'units_shipped_t30',
  'units_shipped_t60',
  'units_shipped_t90',
  'open_pos',
  'sell_through',
  'dos',
  'min_available_qty',
  'max_available_qty',
  'stock_status',
  'instock_rate',
  'no/low_stock_wt_open_pos',
  'no/low_stock_wt_no_open_pos',
  'total_sales',
  'total_units',
  'product_name',
  'product_category',
  'pack_type',
  'pack_size',
  'sc_ideal_price',
  'vc_ideal_price',
  'sales_channel',
  'brand',
  'product_sub_category',
  'vendor_confirmation_%',
  'po_received_amount',
  'po_received_units',
  'receive_fill_rate',
  'overall_vendor_lead_time_(days)',
  'aged_90+_days_sellable_inventory',
  'aged_90+_days_sellable_units',
  'sellable_inventory_amount',
  'unsellable_on_hand_inventory_amount',
  'unsellable_on_hand_units',
  'in_stock_flag',
  'cumulative_instock_days',
  'day_of_month',
  'oos_date',
] as const;

export const PATTEX_MARKETING_COLUMNS = [
  'sku',
  'fnsku',
  'asin',
  'condition',
  'your_price',
  'mfn_listing_exists',
  'mfn_fulfillable_quantity',
  'afn_listing_exists',
  'afn_warehouse_quantity',
  'afn_fulfillable_quantity',
  'afn_unsellable_quantity',
  'afn_reserved_quantity',
  'afn_total_quantity',
  'per_unit_volume',
  'afn_inbound_working_quantity',
  'afn_inbound_shipped_quantity',
  'afn_inbound_receiving_quantity',
  'afn_researching_quantity',
  'afn_reserved_future_supply',
  'afn_future_supply_buyable',
  'store',
  'date',
  'reserved_qty',
  'reserved_customerorders',
  'reserved_fc_transfers',
  'reserved_fc_processing',
  'available_inventory',
  'units_shipped_t30',
  'units_shipped_t60',
  'units_shipped_t90',
  'open_pos',
  'sell_through',
  'dos',
  'min_available_qty',
  'max_available_qty',
  'stock_status',   
  'instock_rate',
  'no/low_stock_wt_open_pos',
  'no/low_stock_wt_no_open_pos',
  'total_sales',
  'total_units',
  'sales_channel',
  'brand',
  'ads_sales',
  'ads_unit_sold',
  'ads_spend',
  'impressions',
  'clicks',
  'click_thru_rate_(ctr)',
  'cost_per_click_(cpc)',
  'total_advertising_cost_of_sales_(acos)',
  'total_return_on_advertising_spend_(roas)',
  'cvr',
  'campaign_name',
  'campaign_type',
  'portfolio_name',
  'product_name',
  'product_category',
  'pack_type',
  'pack_size',
  'sc_ideal_price',
  'vc_ideal_price',
  'product_sub_category',
  'vendor_confirmation_%',
  'po_received_amount',
  'po_received_units',
  'receive_fill_rate',
  'overall_vendor_lead_time_(days)',
  'aged_90+_days_sellable_inventory',
  'aged_90+_days_sellable_units',
  'sellable_inventory_amount',
  'unsellable_on_hand_inventory_amount',
  'unsellable_on_hand_units',
  'in_stock_flag',
  'cumulative_instock_days',
  'day_of_month',
  'oos_date',
] as const;

export const SELLER_CENTRAL_ADS_COLUMNS = [
  'asin',
  'date',
  'impressions',
  'clicks',
  'spend',
  'sales',
  'orders',
  'units',
  'conversion_rate',
  'cpc',
  'roas',
  'acos',
  'campaign_name',
  'portfolio_name',
  'report_type',
  'product_name',
  'category',
  'pack_type',
  'pack_size',
  'sc_ideal_price',
  'vc_ideal_price',
  'total_sales',
] as const;

export const VENDOR_CENTRAL_ADS_COLUMNS = [
  'asin',
  'date',
  'impressions',
  'clicks',
  'spend',
  'sales',
  'orders',
  'units',
  'conversion_rate',
  'cpc',
  'roas',
  'acos',
  'campaign_name',
  'portfolio_name',
  'report_type',
  'product_name',
  'category',
  'pack_type',
  'pack_size',
  'sc_ideal_price',
  'vc_ideal_price',
  'total_sales',
] as const;

export const NOON_MINUTES_ADS_COLUMNS = [
  'date',
  'sku',
  'clicks',
  'spends',
  'revenue',
  'orders',
  'total_sales',
] as const;

export const NOON_MINUTES_INVENTORY_COLUMNS = [
  'date',
  'zsku',
  'inventory',
  'product_name',
  'category',
  'pack_size',
  'last_30_day_sale_qty',
  'dos',
] as const;

export const NOON_MINUTES_SALES_COLUMNS = [
  'date',
  'zsku',
  'qty_sold',
  'total_sales',
  'product_name',
  'category',
  'pack_size',
] as const;

export const NOON_CORE_ADS_COLUMNS = [
  'sku',
  'date',
  'views',
  'clicks',
  'orders',
  'atc',
  'spends',
  'revenue',
  'ctr',
  'roas',
  'cpc',
  'cps',
  'cvr',
  'channel',
] as const;

export const NOON_CORE_INVENTORY_COLUMNS = [
  'date',
  'sku',
  'brand',
  'inventory_type',
  '_',
  'express_(fbn)',
  'supermall',
  'market',
  'product_name',
  'category',
  'pack_size',
  'last_30_day_sale_qty',
  'sell_thru',
  'dos',
] as const;

export const NOON_CORE_SALES_COLUMNS = [
  'date',
  'sku',
  'brand',
  'partner_sku',
  'total_sales',
  'quantity',
] as const;

export const META_ADS_UK_COLUMNS = [
  'country',
  'campaign_name',
  'date',
  'impression',
  'reach',
  'clicks',
  'ads_spend',
  'order',
  'ads_sales',
  'adds_to_cart',
  'checkouts_initiated',
  'adds_of_payment_info',
  'frequency',
  'ctr',
  'cpc',
  'cpm',
  'cost_per_result',
  'average_purchase_value',
  'roas',
  'reporting_starts',
  'reporting_ends',
  'date_raw',
  'reporting_starts_raw',
  'reporting_ends_raw',
] as const;

export const GOOGLE_ADS_UK_COLUMNS = [
  'date',
  'campaign',
  'impression',
  'clicks',
  'ctr',
  'currency_code',
  'ads_spend',
  'conversions',
  'ads_sales',
  'conversion_rate',
  'acos',
  'roas',
  'country',
] as const;

export const KINETICA_AMAZON_ADS_COLUMNS = [
  'asin',
  'date',
  'report_type',
  'campaign_name',
  'product_category',
  'impressions',
  'clicks',
  'spend',
  'sales',
  'orders',
  'units',
  'acos',
  'roas',
  'conversion_rate',
  'quantity',
  'overall_sale',
] as const;

export function validateColumns(fileColumns: string[], requiredColumns: readonly string[]) {
  const requiredSet = new Set(requiredColumns);
  const fileSet = new Set(fileColumns.map(normalizeColumnName));

  const missingColumns = requiredColumns.filter((col) => !fileSet.has(col));
  const extraColumns = [...fileSet].filter((col) => !requiredSet.has(col));

  return {
    valid: missingColumns.length === 0,
    missingColumns,
    extraColumns,
  };
}
